### ISSUE TITLE
generic/arch: Wrong virtualbox modules installed

### ISSUE THREAD

**Issue by AngellusMortis** [lavabit/robox#1]
https://github.com/lavabit/robox/blob/master/scripts/arch/virtualbox.sh#L10

    pacman --sync --noconfirm virtualbox-guest-utils-nox

Should be 

    pacman --sync --noconfirm virtualbox-guest-modules-arch virtualbox-guest-utils-nox 

Without specifying the guest modules to install, it is defaulting to `virtualbox-guest-dkms`, which does not work with a Linux kernal.

**Comment by ladar** [comment]
Thank you. I've updated the script, and it will be used the next time I build the box.
