### ISSUE TITLE
More architectures!

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#10]
Could we get boxes for more architectures, to help test applications in different environments? I think most of these boxes are amd64, which is awesome, and i386, powerpc, arm, mips would be great as well!

Unfortunately, most hypervisors do not currently support non-x86-based guests. Though I think it is possible to run some non-x86 guest boxes with Vagrant, via the Vagrant libvirt plugin. This enables users to run non-x86 guests on x86 hosts, though the hosts must be running (GNU?) Linux natively.

Could we get some libvirt-based ppc, arm, and mips boxes published? These take longer to build and run, but they are worth it for projects that need to test on lots of different architectures.

**Comment by ladar** [comment]
@macandre I've thought about adding alt architecture variants in the past. x32 (aka what others call i386/i686 or x86) and arm64 were on my list. I also toyed with the idea of building a graphical desktop variant for some of the distros (currently the only box I build with a graphical desktop is the `lavabit/magma-developer` images). 

Unfortunately I decided I couldn't justify the time/effort to take that on (you could?). I realized I only need, and/or use x64 images (remember, I started this journey to create test environments for [magma](https://magmadaemon.org/)). Which means if I start building other variants they would be strictly for other people, and as even though I'd like to, it just takes too much time/effort, and occuipies my robots, for too long. My build farm is essentially maxed out already. Adding x32 variants, while probably easy to to do from a code/configuration standpoint, would effectively double my build time from ~3 days to ~6 days... and likely a lot longer to get the initial kinks worked out. 

If I do go down the alt architecture path, it's likely to be arm64 (or ppc) images, but that likely won't come for awhile, and when I'm ready to port magma (or the more likely candidate libdime) to those platforms. 

I've done some limited experiments, trying to build my existing configs for arm, using QEMU (on an x64 host), and while I got a few of the images working, it simply took too long to build/maintain. 

Your welcome to fork/attempt it, but I'm also not sure how much demand there is right now for arm guests? I believe libvirt (aka QEMU) is the only hypervisor (of the 5 I currently target) that is even capable of emulating and/or natively hosting arm guests. I've heard VMWare and Hyper-V are on the way, so we'll see. As for VirtualBox and Parallels, I've heard nothing.

**Comment by mcandre** [comment]
I sliced my pinky unboxing a shiny new System76 Galaga Pro, so I now have a dedicated Linux host for non-x86 tinkering with qemu and libvirt. I uploaded a work in progress branch of my templates to document my progress configuring Packer for ARM guests...

https://github.com/mcandre/packer-templates/issues/153

Doesn't quite work. The current error is something about qemu unable to set boot device list (?) I'll keep trying...

**Comment by mcandre** [comment]
Added basic, working Packer configuration for ppc64el Debian guest box:

https://github.com/mcandre/packer-templates

Plan to eventually return to my packer templates and get ppc (32-bit), ppc64 (high endian?), arm, mips, sparc... boxes going for Debian and other OS's. For now I'm busy enough trying to get `vagrant export` to not corrupt ppc guests :P

**Comment by mcandre** [comment]
Good news, able to get a basically working alternate architecture guest running with Packer + Vagrant. See the ppc64el build of Debian:

https://github.com/mcandre/packer-templates/tree/master/debian

Many quirks to sort out, such as an open issue about file permissions during `vagrant package`. Works on My Machine^TM

**Comment by mcandre** [comment]
Note that x32 is actually distinct from i{3,4,5,6}86 = Intel 8086 = x86. The latter are strictly limited to classic registers, while x32 is a variant of x86_64 = amd64 in which the 64-bit registers are available, but pointers are restricted to 32 bits.

There is some ambiguity between i386 vs. i486 vs. i586 vs. i686--the Linux kernel hasn't supported pure i386 CPU's for some time now. And so some people use the more specific i(4/5/6)86 name to clarify when software components are intended for more modern 32-bit Intel x86 platforms (e.g. i686). But alas, people are lazy and tend to write i386 or x86 or 32-bit when they mean i586+ versions of 8086.

By the way, I'd still like to see i386 boxes published for completeness, as a more reliable way to test 32-bit applications. Many compiler setups like plain vanilla gcc can often create 8086 executables, however there is often no good way to test these without access to a true 32-bit machine, either vintage hardware or virtual machines.

The good news is that OS developers are rapidly dropping support for both x32 and 8086 platforms. CentOS dropped support for 8086, the Linux kernel is dropping support for x32, Ubuntu dropped support for 8086. FreeBSD 8086 doesn't boot, DragonflyBSD and HardenedBSD don't do 8086, SmartOS doesn't do 8086. macOS is even dropping support for 8086 applications, requiring developers to assume a full amd64 userland.

In contrast, MINIX and MirOS have not yet been ported to amd64, forming some of the rare stragglers. They might run on a 64-bit CPU, but it's safer to apply a 32-bit environment just in case. Some embedded systems, including medical devices, are sure to be stuck on 8086 indefinitely. 

For these reasons, it would be helpful to have 32-bit VM's. Roboxes' 64-bit images are tremendously helpful as is. I just hope we can find the capacity to cover these marginal gaps, for users who (for whatever reason) require good old, 2^5 computing.

**Comment by ladar** [comment]
I have no issue with accepting a PR that adds an i386, ppc, or arm64 variant to the repo, and including them in the build pipeline (assuming they can be built on CentOS 7 + x86_64). 

But since I personally don't have a need for i386/i586/arm configs (at the moment), it'll be hard for me to find the time to port the configs over, and test them.
