### ISSUE TITLE
vagrant up gets prompt for grub-pc on generic/ubuntu1804

### ISSUE THREAD

**Issue by bogn83** [lavabit/robox#105]
Running `vagrant up` on several of the latest versions of `generic/ubuntu1804` yields below "error"/unexpected interactive prompt for grub-pc (the host being ubuntu itself):
```
    default: Package configuration
┌──────────────────────────┤ Configuring grub-pc ├──────────────────────────┐│
││ The GRUB boot loader was previously installed to a disk that is no
││ longer present, or whose unique identifier has changed for some reason.   
││ It is important to make sure that the installed GRUB core image stays in  
││ sync with GRUB modules and grub.cfg. Please check again to make sure
││ that GRUB is written to the appropriate boot devices.
││
││ If you're unsure which drive is designated as boot drive by your BIOS,    
││ it is often a good idea to install GRUB to all of them.
││
││ Note: it is possible to install GRUB to partition boot records as well,   
││ and some appropriate partitions are offered here. However, this forces    
││ GRUB to use the blocklist mechanism, which makes it less reliable, and    
││ therefore is not recommended.
││
││<Ok>
│││
```

**Original output excerpt with no added line breaks** <details>
  <summary>Click to expand!</summary>

  ```
    default: Package configuration┌──────────────────────────┤ Configuring grub-pc ├──────────────────────────┐│││ The GRUB boot loader was previously installed to a disk that is no││ longer present, or whose unique identifier has changed for some reason.   ││ It is important to make sure that the installed GRUB core image stays in  ││ sync with GRUB modules and grub.cfg. Please check again to make sure││ that GRUB is written to the appropriate boot devices.││││ If you're unsure which drive is designated as boot drive by your BIOS,    ││ it is often a good idea to install GRUB to all of them.││││ Note: it is possible to install GRUB to partition boot records as well,   ││ and some appropriate partitions are offered here. However, this forces    ││ GRUB to use the blocklist mechanism, which makes it less reliable, and    ││ therefore is not recommended.││││<Ok>│││
```
</details>

# Details

The only non-100%-vanilla thing I do is inline-shell provisioning with
```
apt-get update
apt-get dist-upgrade -y
```

Doing
```
echo "set grub-pc/install_devices /dev/sda" | debconf-communicate
```
before the apt update and dist-upgrade actually fixes it, but shouldn't be necessary I guess and apparently wasn't in the past.

This was tested and experienced with the following versions of `generic/ubuntu1804`:
* 2.0.6
* 2.0.4
* 2.0.0
* 1.9.40
* 1.9.18
* 1.8.60

**Comment by malefice** [comment]
I can confirm that (a) this issue exists in the latest box version  (even with just `apt-get upgrade`) and (b) the workaround works.

**Comment by ladar** [comment]
I need more info. Specifically which provider are you using? I'm guessing `libvirt` and this is related to issue #125 ... 

Basically what's happening is Vagrant is creating a VM with a virtual disk that doesn't match the one created by `packer` ... what I don't know off-hand is whether it's simply mismatched device name, or the device requires a kernel module that wasn't part of the image installed on the grub partition. In other words the issue discussed in #125.

I'm going to close this... on the assumption it's part of the larger problem. But if I'm wrong, please re-open with more info.
