### ISSUE TITLE
su - to root on generic/openbsd6? 

### ISSUE THREAD

**Issue by cellarweasel** [lavabit/robox#107]
Hello, 
this is perhaps just a silly question, but how does a person su or sudo up to root? I used the generic/openbsd and generic/centos7 and I'm just wondering if that is baked in the image but I'm just missing something or if more serious modifications are needed?

**Comment by mkinney** [comment]
Just use "sudo su -"

**Comment by ladar** [comment]
Yup, the `root` account has a randomized password. So you need to login as `vagrant` and run `sudo su`.
