### ISSUE TITLE
Plan 9?

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#12]
Could we get a Plan 9 box? Would be awesome to quickly build and test apps in a Plan 9 VM!

**Comment by ladar** [comment]
@mcandre If you really want a challenge, build a GNU/Hurd system. I'm afraid Plan 9 is in the nostalgia category, right next to its brother Inferno. FreeDOS and OpenSolaris are on my list, but at least for now, my  focus is on distros which would make suitable hosts for magma. 

Pull request?

**Comment by mcandre** [comment]
Speaking of OpenSolaris, I have a working SmartOS template

https://github.com/mcandre/packer-templates/tree/master/smartos

The SmartOS install process was cumbersome enough that I had to fork and submit a PR just for it lol

**Comment by ladar** [comment]
@mcandre I don't understand. You forked `packer`, `SmartOS` or your template?

**Comment by mcandre** [comment]
just packer lol, don't get crazy
