### ISSUE TITLE
Some BSD boxes having hostname `bazinga`

### ISSUE THREAD

**Issue by timschumi** [lavabit/robox#124]
Some of the BSD boxes (more precisely: `freebsd11`, `freebsd12`, `hardenedbsd11`, `hardenedbsd12` and `openbsd6`) still have a placeholder hostname of "bazinga" instead of the box name.

**Comment by AnthonyMastrean** [comment]
Seems to be some kind of pattern in these hostname scripts. I don't fully understand the circumstances that will result in that last if block being called.

https://github.com/lavabit/robox/blob/master/scripts/freebsd11/hostname.sh#L11-L15

**Comment by timschumi** [comment]
Turns out that the underlying issue was that some script commands were missing their environment variables, resulting in some hostname scripts defaulting to "bazinga" (e.g. [freebsd11-libvirt](https://github.com/lavabit/robox/blob/806fc9412a9a4164945b106f5f6ae53741d3baa2/generic-libvirt.json#L669) compared to [rhel6-libvirt](https://github.com/lavabit/robox/blob/806fc9412a9a4164945b106f5f6ae53741d3baa2/generic-libvirt.json#L952)).
