### ISSUE TITLE
Box for BOINC

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#137]
The BOINC project (Rosetta@Home) can help find a vaccine for COVID-19. Can we get a box packed with BOINC preinstalled and ready to authenticate new users?

https://boinc.bakerlab.org/

**Comment by ladar** [comment]
@mcandre can you send me a setup/config module for one of the generic base images? Something like the [lineage.sh](https://github.com/lavabit/robox/blob/master/scripts/ubuntu1604/lineage.sh) module?

**Comment by ladar** [comment]
@mcandre closing... if you're able to work on it, feel free to re-open and/or submit a pull request.
