### ISSUE TITLE
generic/ubuntu2004?

### ISSUE THREAD

**Issue by hswong3i** [lavabit/robox#139]
Since Ubuntu 20.04 LTS is going to be release on 2020-04-23 (see https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule), shall we prepare a new vagrant box for it?

**Comment by abbbi** [comment]
hi,

i have added some stuff for building the libvirt version for ubuntu 20.04. With some minor changes it worked quite well for me.

**Comment by abbbi** [comment]
Box for testing (libvirt) at: https://app.vagrantup.com/abi/boxes/ubuntu2004

**Comment by ladar** [comment]
Done! Assuming the new config builds properly, it will get pushed as part of the 3.0.0 release.
