### ISSUE TITLE
How often are VM's rebuilt?

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#148]
From a security perspective, scheduling automatic rebuild, republish about every two weeks would be a good way to ward off vulnerabilities.

**Comment by ladar** [comment]
@mcandre the goal is roughly every ~2 weeks. However it varies widely depending on whether I can monopolize the build servers, my time, and how many issues I run into. 

I would _like_ to setup dedicated hardware that automatically rebuilds boxes on a fixed schedule, such as every 1-3 days for the popular boxes like CentOS, with weekly updates for the out of date distro versions, etc. And have that infrastructure auto test/upload the box files if they all pass. But that hasn't happened yet.
