### ISSUE TITLE
generic/arch seems to have an invalid /etc/fstab

### ISSUE THREAD

**Issue by mrc0mmand** [lavabit/robox#152]
In the `generic/arch` image (v3.0.8) I noticed that the ssh setup/login takes painfully long and some of our tests, which use the image, started failing. The issue seems to be in `/etc/fstab` which uses `/dev/sda*`, but the VM itself uses `/dev/vda*`:

```
[root@arch vagrant]# cat /etc/fstab
# Static information about the filesystems.
# See fstab(5) for details.

# <file system> <dir> <type> <options> <dump> <pass>
# UUID=eee2dc44-6f04-4163-a1cd-52d1c9594a28
/dev/sda2           	/         	ext4      	rw,relatime	0 1

# UUID=3380d0c2-6919-4838-ac90-a6e40d1218b7
/dev/sda1           	none      	swap      	defaults  	0 0
```

```
[root@arch vagrant]# lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
vda    254:0    0  32G  0 disk 
├─vda1 254:1    0   4G  0 part 
└─vda2 254:2    0  28G  0 part /
```

```
[root@arch vagrant]# systemctl status dev-sda1.device
● dev-sda1.device - /dev/sda1
     Loaded: loaded
     Active: inactive (dead)

Jun 06 17:46:57 arch.localdomain systemd[1]: dev-sda1.device: Job dev-sda1.device/start failed with result 'timeout'.
Jun 06 17:48:27 arch.localdomain systemd[1]: dev-sda1.device: Job dev-sda1.device/start timed out.
Jun 06 17:48:27 arch.localdomain systemd[1]: Timed out waiting for device /dev/sda1.
Jun 06 17:48:27 arch.localdomain systemd[1]: dev-sda1.device: Job dev-sda1.device/start failed with result 'timeout'.
Jun 06 17:49:58 arch.localdomain systemd[1]: dev-sda1.device: Job dev-sda1.device/start timed out.
Jun 06 17:49:58 arch.localdomain systemd[1]: Timed out waiting for device /dev/sda1.
Jun 06 17:49:58 arch.localdomain systemd[1]: dev-sda1.device: Job dev-sda1.device/start failed with result 'timeout'.
Jun 06 17:51:40 arch.localdomain systemd[1]: dev-sda1.device: Job dev-sda1.device/start timed out.
Jun 06 17:51:40 arch.localdomain systemd[1]: Timed out waiting for device /dev/sda1.
Jun 06 17:51:40 arch.localdomain systemd[1]: dev-sda1.device: Job dev-sda1.device/start failed with result 'timeout'.
```

```
[root@arch vagrant]# systemctl status dev-vda1.device
● dev-vda1.device - /dev/vda1
   Follow: unit currently follows state of sys-devices-pci0000:00-0000:00:03.0-virtio0-block-vda-vda1.device
     Loaded: loaded
     Active: active (plugged) since Sat 2020-06-06 17:45:27 UTC; 10min ago
     Device: /sys/devices/pci0000:00/0000:00:03.0/virtio0/block/vda/vda1
```

This seems to be caused by the recent move from the `scsi` disk bus driver to `virtio`. If I explicitly override the disk bus driver in the Vagrantfile, the issues goes away (since the root device is now `/dev/sda*`).

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.provider :libvirt do |libvirt|
    libvirt.disk_bus = "scsi"
  end
end
```

```
[vagrant@arch ~]$ cat /etc/fstab
# Static information about the filesystems.
# See fstab(5) for details.

# <file system> <dir> <type> <options> <dump> <pass>
# UUID=eee2dc44-6f04-4163-a1cd-52d1c9594a28
/dev/sda2           	/         	ext4      	rw,relatime	0 1

# UUID=3380d0c2-6919-4838-ac90-a6e40d1218b7
/dev/sda1           	none      	swap      	defaults  	0 0

[vagrant@arch ~]$ lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0  32G  0 disk 
├─sda1   8:1    0   4G  0 part [SWAP]
└─sda2   8:2    0  28G  0 part /
```

**Comment by timschumi** [comment]
Yikes. I'll take a look. I'm also surprised that it didn't fail outright during our tests.

Hopefully, this can be fixed just by adding the `-U` flag (for UUID-based mounting) to the genfstab call [here](https://github.com/lavabit/robox/blob/6ee39eaf8e11b01b0968ce43fc99fca35c065eb7/http/generic.arch.vagrant.sh#L31).

Nothing that you can do right now, but I'll hopefully get around to making a test build and opening a PR today.

**Comment by mrc0mmand** [comment]
Whoops, sorry for the reopen.


> Yikes. I'll take a look. I'm also surprised that it didn't fail outright during our tests.
> 
> Hopefully, this can be fixed just by adding the `-U` flag (for UUID-based mounting) to the genfstab call [here](https://github.com/lavabit/robox/blob/6ee39eaf8e11b01b0968ce43fc99fca35c065eb7/http/generic.arch.vagrant.sh#L31).
> 
> Nothing that you can do right now, but I'll hopefully get around to making a test build and opening a PR today.

Thanks for looking into this! Also, no worries, I use the image as a base for a custom one (with necessary test/build dependencies), so in the meantime I just fixed the fstab *manually*.

**Comment by ladar** [comment]
@mrc0mmand @timschumi I accepted the patch (but haven't tested it out yet). Either way, I just wanted to give you a heads up, the `3.0.10` boxes have already been built, so despite being uploaded after accepting this PR, they won't have this change. It should make it into the `3.0.12` build.

Thanks for reporting the issue. I'm sorry we broke your Vagrantfile, but if you're curious, look at issue #125 for why we made the change.

**Comment by mrc0mmand** [comment]
> @mrc0mmand @timschumi I accepted the patch (but haven't tested it out yet). Either way, I just wanted to give you a heads up, the `3.0.10` boxes have already been built, so despite being uploaded after accepting this PR, they won't have this change. It should make it into the `3.0.12` build.
> 
> Thanks for reporting the issue. I'm sorry we broke your Vagrantfile, but if you're curious, look at issue #125 for why we made the change.

Thanks for the heads up! I definitely grok the reason after the scsi/virtio change, so I'm glad finding this issue *nudged* it further in that direction.
