### ISSUE TITLE
Typo on Roboxes.org

### ISSUE THREAD

**Issue by oxr463** [lavabit/robox#160]
> Robxes is maintained by Ladar Levison. Infrastructure for this project is provided by Hacking and Coffee LLC, and Lavabit LLC.
> --https://roboxes.org/#bugs-and-issues

Shouldn't that be Roboxes?

**Comment by oxr463** [comment]
Duplicate of: https://github.com/lavabit/robox/issues/117

Perhaps the site needs to be regenerated?

**Comment by ladar** [comment]
Thank @oxr463 ... nice catch. Fixed.
