### ISSUE TITLE
Update to openSUSE 15.2?

### ISSUE THREAD

**Issue by hswong3i** [lavabit/robox#162]
Refer to https://github.com/lavabit/robox/issues/133#issuecomment-622121630

> As an aside, the OpenSUSE config could also use improvement. It's currently stuck on 15.1 because 15.2 wasn't working (when I built the 2.0.6 images, haven't tried since). And it doesn't nearly as many tweaks/improvements as some of the other guests.

@ladar Shall we give another try to openSUSE 15.2 again, as it is now officially released (https://doc.opensuse.org/release-notes/x86_64/openSUSE/Leap/15.2/)?

**Comment by ladar** [comment]
There was a small issue that delayed the updated. But I fixed it, and the configs are updated. If all goes well, I'll try to include updates box images for VMWare/VirtualBox/libvirt with the`3.0.22` release. The other platforms should get updated in the next build.
