### ISSUE TITLE
RHEL8: does not boot with disk_bus=scsi

### ISSUE THREAD

**Issue by abbbi** [lavabit/robox#17]
hi,

it appears to have been changed for vmware already, but i was unable to boot the libvirt variant of your rhel8 image with the default setting:

disk_bus=scsi

it times out searching for the root volume and fdisk in rescue mode does not show any disks.
I was able to boot the VM with vagrant-libvirt using

disk_bus="sata"

in the Vagrant File setting.

**Comment by ladar** [comment]
I'm having trouble understanding/duplicating your issue, as all 4 disk modes worked just fine (ide/scsi/sata/virtio). on my system. Is your problem only with rescue mode, or something else? Does the image boot properly if you omit the disk_bus parameter completely and use the default mode?

On my system, via the libvirt GUI, I can set the disk mode to SCSI, but I need to use a `virtio-scsi` disk controller. A plain 'scsi' disk controller doesn't appear to be supported. (At least through the GUI.)

When I test on my system I see:

```bash
# vagrant up --provider libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Checking if box 'generic/rhel8' is up to date...
==> default: Uploading base box image as volume into libvirt storage...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              rhel8-libvirt_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              2
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Memory:            2048M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Nvram:             
==> default:  -- Base box:          generic/rhel8
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/rhel8-libvirt_default.img (32G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        256
==> default:  -- Sound Type:	
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Configuring and enabling network interfaces...
    default: SSH address: 192.168.121.108:22
    default: SSH username: vagrant
    default: SSH auth method: private key
```

The command line spawned on my system, without an explicit disk bus, appears to automatically be set to `virtio-scsi` but that could be a by-product of my host/libvirt/qemu/vagrant/vagrant-libvirt version(s).

```bash
# ps -ef | grep rhel8
qemu     12112     1 65 03:30 ?        00:00:07 /usr/libexec/qemu-kvm -name guest=rhel8-libvirt_default,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-31-rhel8-libvirt_defaul/master-key.aes -machine pc-i440fx-rhel7.6.0,accel=kvm,usb=off,dump-guest-core=off -cpu Haswell-noTSX-IBRS,vme=on,ss=on,f16c=on,rdrand=on,hypervisor=on,arat=on,tsc_adjust=on,stibp=on,ssbd=on,xsaveopt=on,pdpe1gb=on,abm=on -m 2048 -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid 8686b1b3-bc0b-4eaf-aade-007c37536f12 -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=31,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x3 -drive file=/var/lib/libvirt/images/rhel8-libvirt_default.img,format=qcow2,if=none,id=drive-scsi0-0-0-0 -device scsi-hd,bus=scsi0.0,channel=0,scsi-id=0,lun=0,drive=drive-scsi0-0-0-0,id=scsi0-0-0-0,bootindex=1 -netdev tap,fd=33,id=hostnet0,vhost=on,vhostfd=34 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:83:89:f1,bus=pci.0,addr=0x5 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -vnc 127.0.0.1:0 -k en-us -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x4 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
```

**Comment by ladar** [comment]
@abbbi can you provide more information please?

**Comment by abbbi** [comment]
its not working if disk mode is set to scsi. Bootup has a timeout while waiting for the root device, dracut is ending up in the rescue shell, where fdisk -l shows no disk at all.
Vagrant simply hangs at:

==> default: Waiting for domain to get an IP address...

Im running a basic libvirt/qemu setup on debian stretch.

Qemu command line with default setting:

`18577 ?        Sl     0:08 qemu-system-x86_64 -enable-kvm -name guest=rhel8_default,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-7179-rhel8_default/master-key.aes -machine pc-i440fx-2.8,accel=kvm,usb=off,dump-guest-core=off -cpu Westmere,+vme,+ds,+acpi,+ss,+ht,+tm,+pbe,+pclmuldq,+dtes64,+monitor,+ds_cpl,+vmx,+smx,+est,+tm2,+xtpr,+pdcm,+pcid,+dca,+arat,+pdpe1gb,+rdtscp -m 2048 -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid aea2f032-4c96-4e65-b9cc-73384a8160b6 -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-7179-rhel8_default/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -device lsi,id=scsi0,bus=pci.0,addr=0x3 -drive file=/var/lib/libvirt/images/rhel8_default.img,format=qcow2,if=none,id=drive-scsi0-0-0 -device scsi-hd,bus=scsi0.0,scsi-id=0,drive=drive-scsi0-0-0,id=scsi0-0-0,bootindex=1 -netdev tap,fd=54,id=hostnet0,vhost=on,vhostfd=57 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:c7:f5:e9,bus=pci.0,addr=0x5 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -vnc 127.0.0.1:16 -k en-us -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x4 -msg timestamp=on
`

qemu command with disk_bus="sata" set in the Vagrantfile, which boots fine:

`24223 ?        Sl     0:00 qemu-system-x86_64 -enable-kvm -name guest=rhel8_default,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-7182-rhel8_default/master-key.aes -machine pc-i440fx-2.8,accel=kvm,usb=off,dump-guest-core=off -cpu Westmere,+vme,+ds,+acpi,+ss,+ht,+tm,+pbe,+pclmuldq,+dtes64,+monitor,+ds_cpl,+vmx,+smx,+est,+tm2,+xtpr,+pdcm,+pcid,+dca,+arat,+pdpe1gb,+rdtscp -m 2048 -realtime mlock=off -smp 2,sockets=2,cores=1,threads=1 -uuid 899013c1-1e60-4feb-b385-511b4b20ff37 -no-user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-7182-rhel8_default/monitor.sock,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2 -device ahci,id=sata0,bus=pci.0,addr=0x3 -drive file=/var/lib/libvirt/images/rhel8_default.img,format=qcow2,if=none,id=drive-sata0-0-0 -device ide-hd,bus=sata0.0,drive=drive-sata0-0-0,id=sata0-0-0,bootindex=1 -drive file=/local_iso/rhel-8.0-beta-1-x86_64-dvd.iso,format=raw,if=none,id=drive-ide0-0-0,readonly=on -device ide-cd,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0 -netdev tap,fd=32,id=hostnet0,vhost=on,vhostfd=35 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:fe:4d:6d,bus=pci.0,addr=0x5 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -vnc 127.0.0.1:1 -k en-us -device cirrus-vga,id=video0,bus=pci.0,addr=0x2 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x4 -msg timestamp=on

`

**Comment by ladar** [comment]
@abbbi it appears your config is using the LSI SCSI disk controller. can you try booting with a virtio-scsi controller? I'm not sure what the option for this would be, but it might be `disk_bus = "virtio"` or `disk_bus = "virtio-scsi"`... 

My system calls the `qemu-kvm` executable directly instead of going through the generic `qemu-system-x86_64` interface. I don't know if that is having an effect or not.

**Comment by abbbi** [comment]
virtio-scsi does not work, as it seems underlying libvirt verison not beeing supportive:

virDomainDefineXML failed: unsupported configuration: unknown disk bus type 'virtio-scsi'

with bus-type "virtio" it works, too.

**Comment by abbbi** [comment]
Yes, disk_bus="virtio" may be a better default in the templates.

**Comment by ladar** [comment]
@abbbi I updated the RHEL 8 template to use 'virtio' so it becomes part of the 1.8.52 build (which is ongoing). 

On your system, do you have problems with the CentOS 6/7, Oracle 7, or RHEL 6/7 images? Or is the issue limited to RHEL 8?

I suspect the latter, because the beta kernel dropped support for the emulated LSI controller, but was hoping you could confirm?
