### ISSUE TITLE
Default "/vagrant" Shared Folder missing from generic/arch, roboxes/arch

### ISSUE THREAD

**Issue by iocouto** [lavabit/robox#190]
The standard `/vagrant` sync shared folder is not setup for Arch Linux - neither when using the generic/arch nor roboxes/arch, on VirtualBox. 

```
$ vagrant init generic/arch
$ vagrant up
[...]
$ vagrant ssh
[vagrant@arch ~]$ ls -A /
bin   dev  home  lib64       mnt  proc  run   srv  tmp  var
boot  etc  lib   lost+found  opt  root  sbin  sys  usr
```

No 'vagrant' folder...

For comparison, using archlinux/archlinux:

```
$ vagrant init archlinux/archlinux
$ vagrant up
[...]
$ vagrant ssh
[vagrant@archlinux ~]$ ls -A /
bin   dev  home  lib64  opt   root  sbin  swap  tmp  vagrant
boot  etc  lib   mnt    proc  run   srv   sys   usr  var
```

**Comment by timschumi** [comment]
The `/vagrant` folder being present in a box is not required since it's just an arbitrary path. Creating that folder is handled by Vagrant itself when something tries to mount there.

**Comment by timschumi** [comment]
I have tested this on libvirt and VirtualBox, and everything seems to work as expected.

After creating a new Vagrantfile, no folder and no mount is present.

After you add the shared folder to the Vagrantfile, the folder gets created automatically and the directory from the host is mounted inside.

**Comment by justinkb** [comment]
Might be VMware specific then. But then I don't know what the original
person who opened the ticket did wrong, since they are using virtualbox.

I have since resolved my problem, one needs to manually pass
enableSharedFolders (once) to the VM with a VMware cli tool, since the
vagrant VMware plugin fails to do so

**Comment by ladar** [comment]
Looks like the problem has been fixed. Closing.
