### ISSUE TITLE
RHEL6 - Error trying ssh command

### ISSUE THREAD

**Issue by adrianovieira** [lavabit/robox#193]
RHEL6 - Error trying ssh command: `vagrant ssh`

- provider: libvirt
- box: `generic/rhel6` (or `roboxes/rhel6`)

steps to reproduce:

1. `vagrant init -m generic/rhel6` (or `vagrant init -m generic/rhel6 --box-version 3.1.24`)
1. `vagrant up`
1. `vagrant ssh`

   ```
   vagrant@<IP>: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
   ```

env info:

```
O.S.: fedora-33
Vagrant:  2.2.9
vagrant-libvirt (0.1.2, system)
```

**Comment by abbbi** [comment]
you probably hit this one: https://rwmj.wordpress.com/2022/08/08/ssh-from-rhel-9-to-rhel-5-or-rhel-6/

**Comment by ladar** [comment]
Yeah, the issue isn't the RHEL 6 image. It's the nweer host which has disabled RSA based authentication.

**Comment by ladar** [comment]
The short version of the fix:

```
sudo update-crypto-policies --set LEGACY && sudo reboot
```
