### ISSUE TITLE
Add Rocky Linux

### ISSUE THREAD

**Issue by mattboston** [lavabit/robox#194]
Rocky Linux is a new distro that will be taking the place of CentOS.  Could you add this to your list of supported distros?

**Comment by DirtySoc** [comment]
I started getting RockyOS working on my local machine with the hyper-v provisioner. It will also involve changing quite a bit of scripts files and doing a find/replace for `CentOS` to `Rocky`. You can also use the boot.iso for Rocky instead of the dvd1.iso currently used by the centos config.

**Comment by ladar** [comment]
Rocky 8/9 are both part of the pipeline. I even added container images.
