### ISSUE TITLE
Stuck at Waiting for SSH to become available...

### ISSUE THREAD

**Issue by lentzi90** [lavabit/robox#2]
I'm unable to get generic/ubuntu1804 and generic/ubuntu1604 to work properly with libvirt.

Steps to reproduce:
1. `vagrant init generic/ubuntu1804`
2. `vagrant up --provider=libvirt`

Vagrant gets stuck at `Waiting for SSH to become available...` but I can see that the VM has booted successfully in virt-manager.
I have previously used the ubuntu1604 box successfully on this computer and I'm unsure what has happened.
The same problem is not present when using virtualbox as provider.

**Environment**
Host OS: Ubuntu 18.04
Vagrant: 2.0.1
libvirt: 4.0.0
QEMU emulator version 2.11.1

**Comment by ladar** [comment]
I went ahead and revoked the v1.8.20 build util I have time to investigate, so 1.8.14 is now the default. It's about ~2 weeks old. I also made a typo in the above command. It should have been:

vagrant init --box-version 1.8.14 generic/ubuntu1804 && vagrant up --provider libvirt

**Comment by lentzi90** [comment]
Thanks for the help!
The old version worked fine :)
