### ISSUE TITLE
Any plans on providing a fedora 34 box (we use the Vagrant provider)?

### ISSUE THREAD

**Issue by vrubiolo** [lavabit/robox#201]
Hi there,

We are using `generic/fedora33` boxes w/ Vagrant for internal testing and I was wondering if you had any plans on adding a fedora 34 variant now that the distro has been released. 

If you need help on the matter, I'd certainly be interested in chiming in to assist, for instance for validation purposes.

Thanks for the feedback!

**Comment by vrubiolo** [comment]
Ping! Are there any news on this?

**Comment by vrubiolo** [comment]
Ok, it looks like this might be coming from Ladar, cf https://github.com/lavabit/robox/commit/992b218a7002ece869e6809a9fbf4850fe9390c8

**Comment by ladar** [comment]
@vrubiolo I've been working on a new release, but it's taking longer than normal because of all breakages in existing configs, plus having to troubleshoot issues with all of the new configs ... like Fedora 34. Hopefully soon.

**Comment by vrubiolo** [comment]
> @vrubiolo I've been working on a new release, but it's taking longer than normal because of all breakages in existing configs, plus having to troubleshoot issues with all of the new configs ... like Fedora 34. Hopefully soon.

Thanks for taking to the time to reply, despite all those things going on. I'll be looking forward to the boxes being enabled, let me know if you need some testing feedback in the meantime!
