### ISSUE TITLE
generic/alpine314 won't boot properly

### ISSUE THREAD

**Issue by ierturk** [lavabit/robox#207]
`generic/alpine314` won't boot properly under the following environment

- macOS Catalina
- VmWare Fusion 12
- Vagrant 2.2

According to the start up messages on `VM GUI`, under the configuration above the services `open-vm-tools` and `sshd` won't start de to a `network` problem and `vagrant up` command try to connect to VM infinitely. The VM starts after the services is started manually from the `VM GUI`. Also when the `open-vm-tools` is reinstalled, the VM starts properly.

**Comment by ierturk** [comment]
everything is OK when the `net-online` service run level switched to the run level `boot`.

**Comment by ladar** [comment]
Hi @ierturk is this still hapening? I don't have a VMWare Fusion license to test with.

**Comment by ladar** [comment]
@ierturk I could only desk using VMWare desktop on a Linux machine, but there did seem to be a problem with the v3.9 boxes onward, that I hope to have fixed. Look for the `3.4.0` release to upload probably early next week, and if there is still an issue, please reopen the ticket.
