### ISSUE TITLE
bhyve, xhyve providers

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#21]
Could robox offer bhyve, xhyve providers in addition to the other providers, in order to run guests more efficiently on FreeBSD and macOS respectively?

* https://github.com/jesa7955/vagrant-bhyve
* https://github.com/oldpatricka/vagrant-xhyve

**Comment by ladar** [comment]
@mcandre In theory yes, but I don't have any experience with those hypervisors. Can you provide more information? Would I need to the images on FreeBSD/MacOS? Or is it possible to build the image using qemu and export it into a format that will work with those plugins? That's how I generate the docker images.

Can you provide proof a concept/instructions for generating a valid bhyve and a valid xhyve box? If so I can adapt your example to the rest of the box configurations.

**Comment by ladar** [comment]
@mcandre it seems packer doesn't support exporting bhyve/xhyve images. Are you aware of a patch/plugin that does? Or as a last resort, the requisite shell commands?

https://www.packer.io/docs/post-processors/vagrant.html

**Comment by ladar** [comment]
@mcandre are you going to post details?

**Comment by ladar** [comment]
Seems like a nice idea, but the vagrant-xhyve/vagrant-bhyve plugins aren't used by very many people, and are unmaintained... 

I'd like to add more providers... it gives me a warm fuzzy... but if these are providers are going to join the club, they'll have to be maintained by someone else...
