### ISSUE TITLE
ubuntu/2004 3.3.4 broken for at least libvirt

### ISSUE THREAD

**Issue by jason-adnuntius** [lavabit/robox#210]
When using this latest version with libvirt, the up command pauses at 'Waiting for domain to get an IP address...' if I check the console of the box I get the following errors:

![Screenshot from 2021-08-09 10-59-32](https://user-images.githubusercontent.com/52263930/128651409-0c62cf87-c657-4239-9738-2127c0219f11.png)

Reverting to 3.3.2 works fine

**Comment by timschumi** [comment]
No such issue here, on `generic/ubuntu2004` version 3.3.4.

Could you try and redownload the box (i.e. delete it through `vagrant box remove generic/ubuntu2004` and then `vagrant up` again) to see if it may just be a corrupted file on your disk?

**Comment by jason-adnuntius** [comment]
I will give it a go yes.

**Comment by jason-adnuntius** [comment]
This occurred again after re-downloading the libvirt box.

This is only an issue with libvirt, the same version works fine with the virtualbox provider.

Im running on an older processor, I wonder if that could be the reason?

**Comment by jason-adnuntius** [comment]
What versions of packages might you need to determine if its a software or hardware issue on my end?

**Comment by jason-adnuntius** [comment]
actually I have a laptop with a more recent processor I will check if its an issue on there as well

**Comment by jason-adnuntius** [comment]
I tried on a different machine, and its not an issue.    So I guess it must be something about my hardware or software installed.

**Comment by jason-adnuntius** [comment]
For what its worth 3.4.0 of the ubuntu 20.04 image has resolved this issue for me on the one machine where I was getting the error.s
