### ISSUE TITLE
Servicepack flavours for RHEL related builds

### ISSUE THREAD

**Issue by abbbi** [lavabit/robox#218]
hi there,

thanks alot for all your work. Just as a side note: it would be great to have different servicepack flavours
for the RHEL based setups. Sometimes Redhat introduces quite major changes between Servicpack
releases (for example a complete different libvirt/qemu stack). It would be nice to have the flavours
like:

RHEL83
RHEL84
RHEL85..

i usually workaround this by keeping the last version of your images and renaming them if you setup
to release a new rhel8 box with a newer servicepack.

**Comment by ladar** [comment]
Hi @abbbi is this a request just like that in issue #219? Where you want a repo called generic/rhel83, or generic/rhel8-3, etc?

Like I mentioned there, you can simply dictate the robox release in your Vagrantfile and it will stay locked on the same image. For example, `3.5.2` was the last RHEL 8.4 box image. With `3.5.4` it will switch to 8.5. So to stay locked on that image, just add `config.vm.box_version = "3.5.2"` to your Vagrantfile. Something like:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "generic/rhel8"
  config.vm.box_version = "3.5.2"

end
```

You can also use the `--box-version` option with the `vagrant init` command or the `vagrant box add` command and it will use a specific robox release. The former adds the version to the Vagrantfile, while the latter ensures the desired box image is available when you run `vagrant up` which it will then use (although it might warn you that a newer one is available).

**Comment by abbbi** [comment]
@ladar thanks for your reply. I know about the verisons, its just a tedious thing having to follow each version and check if it updates to an new servicepack.
