### ISSUE TITLE
Add Minor version of RHEL to description in generic/rhel8 and generic/rhel7 images

### ISSUE THREAD

**Issue by hunter86bg** [lavabit/robox#219]
Hello All,

Is there any chance to add the minor version of 
RHEL vagrant 'generic/rhel7' and 'generic/rhel8' images' description ?

**Comment by ladar** [comment]
@hunter86bg which description are you referring to? The vagrant cloud descriptions already include the major and minor version numbers, and as far as I know, Red Hat doesn't use a patch level, like the CentOS versioning scheme. 

Are you suggesting we create a generic/rhel7-10 box that stays fixed to 7.10? I've stayed away from that. I figure you can just go back to lock in a box release version that matches what you want, if your that specific. There are also other projects on the Vagrant cloud which release boxes one per version, and then don't update them. But that was one of several reasons I initially created robox project... namely, so wouldn't have to update all my various Vagrantfiles each time there was new minor OS release.

**Comment by ladar** [comment]
@hunter86bg duplicating what I wrote in a similar issue:

Uou can dictate the robox release in your Vagrantfile and it will stay locked on the same image. For example, `3.5.2` was the last RHEL 8.4 box image. With `3.5.4` we will switch to 8.5. So to stay locked on that image, just add `config.vm.box_version = "3.5.2"` to your Vagrantfile, like so:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "generic/rhel8"
  config.vm.box_version = "3.5.2"

end
```

You can also use the `--box-version` option with the `vagrant init` command or the `vagrant box add` command and it will use a specific robox release. The former adds the version to the Vagrantfile, while the latter ensures the desired box image is available when you run `vagrant up` which it will then use (although it might warn you that a newer one is available).

**Comment by hunter86bg** [comment]
I'm already doing that. Yet, You have to go back over the images untill you find a specific minor version of RHEL... And there is no description of which minor version the image 'holds'.
