### ISSUE TITLE
s/conitnue/continue

### ISSUE THREAD

**Issue by lulcat** [lavabit/robox#225]
Hi. don't know how to propose a simple line correction. 

In robox.sh a small typo: 1103s/it/ti  (continue was misspelt as conitnue).

fun fact: I was going to propose publicly as publically, wondering if it might be US English or so. 
Turns out it IS the common term and do not know if I adopted this by virtue of being an ex-pat 
or just due to lack of other Englishmen around :D But we learn something new every day (on a good day at least).

Otherwise, thank you [Mr. Levison] for having been the person that you are and stood up for decency when fascism came knocking. 

Until next time, au revoir.

Sędziwój

**Comment by ladar** [comment]
Hi @lulcat simple changes like this, assuming you are in a browser, just click the fork button, which will copy the repo to your account. Then click branch, and type something simple and descriptive, like `fix-robox.sh-typo`. Then you can click the file you want to edit, and edit it via the website. When your done, click commit. Once you've got a commit, a button called `Create Pull Request` shows up. Click that, and it will open a pull request with the original repos, proposing the change.

If you'd like to try it out, and you're a good well versed in the art and science of writing technical documentation, the `README.md` file needs lots of love. Not romantic love, but rather the the kind of love that results in instructional verbosity. 

At a minimum, it should explain how to use the `robox.sh` script to interact with the box configurations. The `check/check.sh`, `res/providers/providers.sh`, and `res/scripts/add.sh` scripts all could use the same, should you be feeling loquacious. So I ask, Sędziwój, will you help?

P.S. I'll take care of the typo you pointed out. The repo is likely filled with lots of the same, as I often find myself working on this project late at night. A true noctambulist I am. noctambulist

**Comment by ladar** [comment]
@lulcat as it turns out, I made that mistake in four different places!

**Comment by lulcat** [comment]
lol. didn't notice :) anyway Merry Xmas as it's on its way.

**Comment by ladar** [comment]
@lulcat you're welcome. I'm going to close this issue, now that you've seen it. If you can help with the documentation, or anything else, then please open a pull request!
