### ISSUE TITLE
generic/opensuse15: Sharing folders with VMware Workstation on Windows fails

### ISSUE THREAD

**Issue by vohi** [lavabit/robox#233]
Bringing up a vagrant machine using the `generic/opensuse15` box with standard shared folders fails with

```
==> opensuse15: Enabling and configuring shared folders...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "c:\\Users\\...\\generic-opensuse15-vmware.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

Stderr:
```

The same works with the `generic/ubuntu2004` box, it seems that the VMware tools in the OpenSUSE 15 box are out of date.

The provider used here is VMware Workstation 16 Player, with the `vagrant-vmware-desktop` plugin.

**Comment by ladar** [comment]
@vohi looks like the OpenSUSE box is using the OS package, and not building the tools from source. So it appears the OpenSUSE `open-vm-tools` package is either out of date, not being setup correctly, or requires additional packages to work out of the box. If you figure out how to fix this, please submit a PR with the fix. The file you need to change is `scripts/opensuse15/vmware.sh` file.
