### ISSUE TITLE
please add Ubuntu 22.04 Jammy

### ISSUE THREAD

**Issue by evgeni** [lavabit/robox#238]
Ohai,

Ubuntu 22.04 LTS was released (https://ubuntu.com/blog/ubuntu-22-04-lts-released) and it would be cool if you could again provide boxes for it!

Thanks!

**Comment by ladar** [comment]
Hi @evgeni I'm hoping too soon. I was planning on adding Ubuntu 22.04 along with Fedora 36, but the latter keeps getting delayed.

I pushed an initial 22.04 config to the repo, in case you'd like to help test the new config and submit any fixes/improvements back as a pull request. Assuming you have `packer` setup, run:

```
git clone https://github.com/lavabit/robox/ && cd robox
./robox.sh box generic-ubuntu2204-libvirt
```

Substitute `libvirt` for `vmware|virtualbox|parallels|hyperv` as appropriate...

**Comment by evgeni** [comment]
Thanks @ladar!

I'll see if I find some cycles today/tomorrow to give it a spin!

**Comment by evgeni** [comment]
let's start with https://github.com/lavabit/robox/pull/239 ;-)

**Comment by abbbi** [comment]
Built the images and they seem to work fine. It however looks like ubuntu 2204 has snapd enabled by default ([1]), would it make sense to remove it from the images?

[1] https://haydenjames.io/remove-snap-ubuntu-22-04-lts/

**Comment by ladar** [comment]
In case it isn't obvious, the 22.04 config is essentially a copy of the 21.10 config with a bit of string replacement. So the things to be on the lookout for, are any changes that don't get caught automatically by the regular expressions. Particularly anything new/removed that we need/should account for...
