### ISSUE TITLE
Request about naming openbsd boxes

### ISSUE THREAD

**Issue by mlude** [lavabit/robox#24]
Hello,

please name the OpenBSD boxes with the release number like openbsd64 for openbsd 6.4.
OpenBSD releases are numbered with 0.1 increased from release to release.

Regards

**Comment by ladar** [comment]
Hi @mlude I went with the name `openbsd6` because I plan to keep that particular box in sync with the OpenBSD 6.x releases. If I went with the name openbsd64 it would imply the box was going to stay pinned to the 6.4 release branch. 

You should be able to modify the box hostname by adding `config.vm.hostname = "openbsd64.localdomain"` to your Vagrantfile. If you want to ensure you get a particular OpenBSD version, then I'd suggest also pinning your Vagrantfile to a particular robox release.

**Comment by mlude** [comment]
On Tue, Dec 18, 2018 at 09:00:48AM +0000, Ladar Levison wrote:

Hi Ladar,

> Hi @mlude I went with the name `openbsd6` because I plan to keep that
> particular box in sync with the OpenBSD 6.x releases. If I went with
> the name openbsd64 it would imply the box was going to stay pinned to
> the 6.4 release branch. 

yes, I guessed that this would be your intention, but...

There is no major release OpenBSD 6! They simply add 0.1 for each
release. The release after 5.9 became 6.0, then 6.1 and so on. There is
nothing special if the first number changes. That's why I suggested to
name it openbsd64 :-)

> You should be able to modify the box hostname by adding
> `config.vm.hostname = "openbsd64.localdomain"` to your Vagrantfile. If
> you want to ensure you get a particular OpenBSD version, then I'd
> suggest also pinning your Vagrantfile to a particular robox release.

Regards
Markus

**Comment by ladar** [comment]
@mlude my BSD knowledge base goes Linux > Windows > MacOS > FreeBSD > OpenBSD > NetBSD >Solaris. So I appreciate the tidbit on the OpenBSD versioning philosophy. 

I probably won't make any changes now, but perhaps in the future. Just to clarify though, are you suggesting the box name, the host name, or both should be openbsd64?

**Comment by mlude** [comment]
On Tue, Dec 18, 2018 at 10:06:37AM -0800, Ladar Levison wrote:
> @mlude my BSD knowledge base goes Linux > Windows > MacOS > FreeBSD >
> OpenBSD > NetBSD >Solaris. So I appreciate the tidbit on the OpenBSD
> versioning philosophy. 
> 
> I probably won't make any changes now, but perhaps in the future. Just
> to clarify though, are you suggesting the box name, the host name, or
> both should be openbsd64? 

Mainly the box name as there is no OpenBSD 6. Maybe the host name too.

Regards
Markus
