### ISSUE TITLE
Locale not set properly for EL8 Vagrantboxes (centos8, centos8s, alma8, rocky8, oracle8)

### ISSUE THREAD

**Issue by stdevel** [lavabit/robox#262]
I stumbled upon that locales seem to be set incorrectly on EL8 boxes:

```command
# dnf install htop
Failed to set locale, defaulting to C.UTF-8
...
```

This is problematic as some applications (e.g. PostgreSQL database) might break because of this.

The following command fixes this issue:

```command
# dnf install -y langpacks-en glibc-all-langpacks
```

On Oracle Linux 8, this doesn't work. It still shows the same error message.

It seems EL9 is not affected.

**Comment by ladar** [comment]
can you see if this is still a problem, and let me know command should be run to fix it?

**Comment by stdevel** [comment]
I downloaded and tested the following Vagrantboxes:

```command
$ vagrant box list
generic/alma8      (libvirt, 4.2.12)
generic/centos8    (libvirt, 4.2.12)
generic/centos8s   (libvirt, 4.2.12)
generic/oracle8    (libvirt, 4.2.12)
generic/rocky8     (libvirt, 4.2.12)
```

None of the machines have the issue mentioned above anymore. Looks like the missing packages have been installed in the mean time:

```command
$ rpm -qa|grep lang
langpacks-en-1.0-12.el8.noarch
slang-2.3.2-3.el8.x86_64
glibc-langpack-en-2.28-224.el8.x86_64
```

Closing the issue.
