### ISSUE TITLE
openSUSE 15.5 released

### ISSUE THREAD

**Issue by peterdd** [lavabit/robox#277]
Maybe split generic/opensuse15 into

generic/opensuse15.4, generic/opensuse15.5, .. ?

As this is their current yearly release scheme. See https://en.opensuse.org/openSUSE:Roadmap

**Comment by ladar** [comment]
I don't use the OpenSUSE images personally, so I tend to miss changes and/or problems. 

I just pushed a change updating the installer the config to 15.5 but the changes remain untested. If you are an OpenSUSE aficionado, please take a took, and submit a PR with the changes/improvements required.
