### ISSUE TITLE
Linux Integration Services for hyperv

### ISSUE THREAD

**Issue by flybyray** [lavabit/robox#37]
Maybe hyperv templates should install
https://www.microsoft.com/en-us/download/details.aspx?id=55106

**Comment by ladar** [comment]
@flybyray the Hyper-V boxes install the daemons during the OS install phase, as opposed to using a dedicated configuration script/module. This is required, packer depends on the Hyper-V daemons to detect the guest IP address following the OS install reboot (there are 2 exceptions... as those distros currently lack Hyper-V support).

I don't personally use, and/or test, the Hyper-V boxes, so it's quite possible they could use additional tweaking. If you discover they need something, please submit a pull request for a `hyperv.sh` script/module which configures the appropriate distros.

**Comment by ladar** [comment]
@flybyray I'm going to close. Feel free to reopen, if further discussion is required.
