### ISSUE TITLE
vagrant upload fails on ubuntu1804 box when uploading a directory

### ISSUE THREAD

**Issue by vohi** [lavabit/robox#40]
Hi,

I'm managing jobs that I want to execute on a vagrant-managed VM in subdirectories which contain the necessary script files. The ideas is that given a directory jobs/test with files main.sh and other stuff, I can basically just do

$ vagrant upload jobs/test test ubuntu1804

and then run

$ vagrant ssh -c test/main.sh ubuntu1804

This worked nicely for all sorts of images until recently. It works with version 1.8.54, but with the latest version 1.9.2 I get an error from vagrant:

```
/opt/vagrant/embedded/gems/2.2.3/gems/net-scp-1.2.1/lib/net/scp.rb:398:in `await_response_state': scp: error: unexpected filename: . (RuntimeError)
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/channel.rb:610:in `do_close'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:573:in `channel_closed'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:682:in `channel_close'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:549:in `dispatch_incoming_packets'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:249:in `ev_preprocess'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/event_loop.rb:101:in `each'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/event_loop.rb:101:in `ev_preprocess'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/event_loop.rb:29:in `process'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:228:in `process'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:181:in `block in loop'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:181:in `loop'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:181:in `loop'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-ssh-5.1.0/lib/net/ssh/connection/channel.rb:272:in `wait'
	from /opt/vagrant/embedded/gems/2.2.3/gems/net-scp-1.2.1/lib/net/scp.rb:284:in `upload!'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/communicators/ssh/communicator.rb:296:in `block in upload'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/communicators/ssh/communicator.rb:709:in `block in scp_connect'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/communicators/ssh/communicator.rb:489:in `connect'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/communicators/ssh/communicator.rb:707:in `scp_connect'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/communicators/ssh/communicator.rb:293:in `upload'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/commands/upload/command.rb:104:in `block in execute'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/plugin/v2/command.rb:232:in `each'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/commands/upload/command.rb:69:in `execute'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/cli.rb:58:in `execute'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:291:in `cli'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/bin/vagrant:182:in `<main>'
```

Given that the only change is the version of the box, I suspect something in the configuration to have broken things.
I can still upload individual files, but that's not what I need :)

Perhaps you are aware of some changes here that could have broken this?

Cheers,
Volker

**Comment by vohi** [comment]
PS: this is with vagrant 2.2.3 and VirtualBox 5.2.26 (the latter shouldn't matter assuming that this is done via scp rather than VirtualBox's file uploading mechanism).

**Comment by ladar** [comment]
@vohi I did some digging and couldn't find any changes in the build scripts between 1.8.54 and 1.9.2 that would cause this. However, each new box version includes distro updates, and there was a recent update to the OpenSSH package that appears to match your error message:

http://salsa.debian.org/ssh-team/openssh/commits/master

Specifically the following commits:

https://salsa.debian.org/ssh-team/openssh/commit/125924e47db3713a85a70e0f8d6c23818d2ea054
https://salsa.debian.org/ssh-team/openssh/commit/f3357d7941c5ccc3d772e4461b1e2d137909670b

It would take more digging, but assuming the OpenSSH patch is valid, I'm guessing the bug lies with the Vagrant net-ssh package, and how it is sending directory names. 

I'll leave this issue open for now, but you probably want to open up linked bug reports with Vagrant and the Debian SSH team.

**Comment by ladar** [comment]
I did a little testing, and found this combination worked for me. Assuming the directory being uploaded is "scripts" and you want to upload it to the default, "/home/vagrant/":

```
find scripts/ -type d -exec vagrant ssh -c 'mkdir -p {}' \;
find scripts/ -type f -exec vagrant upload {} \;
```

Basically `scp` fails if it's asked to upload to a path that doesn't exist at the destination, so the first command creates all of the necessary subdirectories, and the second uploads each file to the right place.

**Comment by vohi** [comment]
Thanks a bunch @ladar! I'll work around this for now in my script, and have opened a ticket with the Vagrant project.

**Comment by ladar** [comment]
@vohi this Vagrant [pull request](https://github.com/hashicorp/vagrant/pull/10698) claims to have fixed this issue, and the [upstream bug](https://github.com/hashicorp/vagrant/issues/10675#event-2166203320) is closed. Can you test? Unless I hear otherwise from you, I'll assume it's safe to close this issue.

**Comment by vohi** [comment]
Not going to be able to run vagrant from upstream for a while, but fix looks like it would address this issue. Either way, ok to close this issue since there's nothing wrong with the boxes.
