### ISSUE TITLE
Contributing Documentation

### ISSUE THREAD

**Issue by masq** [lavabit/robox#46]
Hey, I stumbled on this project when on the Vagrant store looking for boxes and noticed the generic boxes were all done quite well, but was unable to find some boxes offered by you that I'd like to see. So first off, thank you for this project! Appreciate the work you've put in here.

I made a comment on the other issue where you were asking for the next distros that people would like to see added. But, I would also like to see documentation on how to contribute to the repository if that's not too hard. That way, it wouldn't only be upon you to make boxes, but others could follow your steps so that they can add in the Operating Systems that they'd like to see. Looking at the repo now, it's a little unclear what all needs to happen in order to get another OS added for automated box building.

**Comment by ladar** [comment]
It depends on the operating system you're trying to add. But in broad terms, if you want to add an operating system that is very similar to an existing configuration, it's relatively easy. You can use the `res/scripts/add.sh` script to automate most of the work. For example if you wanted to add CentOS 8, you could run:

```
res/scripts/add.sh centos7 centos8 https://url.tld/centos/iso/c8.iso d818b61f9d8...
```

And the script will copy the existing centos7 configuration in the 5 existing `generic` JSON files, using the new name, and replacing the ISO URL and SHA with the values you provided. It will also copy the auto-install configuration inside the `http` directory, and duplicate the `scripts/centos7` directory (and its contents) as `scripts/centos8`. The script will also replace any instance of the string `centos7` with `centos8` in those files.

It's not perfect, but it gets you started. You'd then need to audit each file and update any relevant params, like repo URLs etc, and make any adjustments, like switching from `service` to `systemctl` (CentOS 6 to 7), or with CentOS 8, switching from `yum` to `dnf`. Once that's done you've got a first commit ready. 

You then need to test the build by running:

```
./robox.sh box generic-NEWNAME-HYPERVISOR
```

Where  NEWNAME is whatever you provided, ie `centos8` and hypervisor is `vmware|virtualbox|hyperv|libvirt|parallels` to test out the config... and refine things as you go. For example you may need to tweak the boot command sequence in the JSON, or some other setting.

Of course if you want to add something completely new, it's the same process you just need to add all the files/update all the JSON by hand. 

Once your done and you've tested the new config on at least 1 hypervisor (preferably several, or even all), submit the pull request, and I'll try and build it on all. Assuming it all looks good, I'll accept, and matches the existing conventions it follows the general pattern, I'll accept. If it's a start, but doesn't follow conventions, I'll add it to a branch so we can refine it (like the evilpot branch/pull request which is trying to add a whole new group of boxes, not a new OS). 

Any questions?

**Comment by ladar** [comment]
P.S. @masq sorry for the delay. I've been overseas, and will be for awhile longer, training a new development team, etc, which has limited the time I have for this project, and cut me off from things like a build farm, high speed connection, etc.

**Comment by ladar** [comment]
@agush / @masq I've added the above notes to the (wiki)[https://github.com/lavabit/robox/wiki] page, so I'm closing this issue. I look forward to reviewing your pull requests.
