### ISSUE TITLE
generic box update: Red Hat Enterprise Linux 8 now generally available

### ISSUE THREAD

**Issue by flybyray** [lavabit/robox#49]
https://developers.redhat.com/blog/2019/05/07/red-hat-enterprise-linux-8-now-generally-available/

generic-hyperv.json
generic-libvirt.json
generic-parallels.json
generic-virtualbox.json
generic-vmware.json

**Comment by lavabit-support** [comment]
I saw that. I just published v1.9.12, so I don't know when I'll be able to create a new version. Work has me on the road for till October and wasn't able to setup remote access for the build bots I normally use to make the images.

**Comment by ladar** [comment]
I saw that. I just published v1.9.12, so I don't know when I'll be able to create a new version. Work has me on the road for till October and wasn't able to setup remote access for the build bots I normally use to make the images.

**Comment by ladar** [comment]
Closing the issue. I did a partial build awhile back, but some of the providers (Hyper-V/Parallels) haven't been rebuilt yet, as I won't have access to all of my build machines again until Oct.
