### ISSUE TITLE
generic/ubuntu1804 kernel panic on boot with virtualbox

### ISSUE THREAD

**Issue by furlongm** [lavabit/robox#53]
Starting a generic/ubuntu1804 vagrant box with VirtualBox with 256M memory gives a kernel panic and an out of memory error on the console, vagrant ssh does not work, and provisioning fails (happens early in the boot process).

This issue does not occur with bento/ubuntu-18.04 or ubuntu/bionic64. Is there a different kernel or kernel options in use, or something else that might cause this?

**Comment by ladar** [comment]
I believe the only custom kernel options in use for that image are `net.ifnames=0 biosdevname=0` ... but the robox install config does include the `linux-tools-$(uname -r) linux-cloud-tools-$(uname -r) linux-cloud-tools-common linux-cloud-tools-generic linux-cloud-tools-virtual` packages, which could be causing the robox version to load additional kernel modules, or use a different kernel version. Those packages are required by the Hyper-V version, but could be removed from the default package set on other hypervisors (I think). 

I suppose there is also a slim chance the other boxes use a different swap configuration, which allows them to swap out data during boot and avoid the error you're seeing, which doesn't happen with the robox (for some unknown reason). 

If you find the culprit, let me know.

**Comment by ladar** [comment]
@furlongm were you able to identify the problem? Or should I close this issue? I assume the image worked just fine with more memory, say 512mb or greater?

**Comment by furlongm** [comment]
Yes it happens in other images too, once the kernel is updated. So this is an Ubuntu issue. Increasing the memory works.
