### ISSUE TITLE
Even more providers!

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#56]
Thank you for maintaining so many operating system base boxes, for so many providers already. Honestly, this is a massive feature matrix to have completed, kudos!

What if we took the boxes and offered them on even more providers, like Amazon/Google Cloud/Azure/Oracle images, as well as Docker and Triton images (where possible)? This could grow the userbase and possibly funding sources a bit further, plugging gaps where no compatible images currently exist. For Docker and Triton builders, we would get a bonus effect of many GNU/Linux guests available as lightweight containers, as opposed to more heavyweight virtual machines.

http://packer.io/docs/builders/index.html

**Comment by ladar** [comment]
@mcandre I would love to release more variants. Earlier this year, I ported several of the generic RH/CentOS/Oracle configs to [Docker](https://hub.docker.com/search?q=roboxes&type=image) but I admittedly haven't spent much time testing/optimizing those images. Ideally all of the Linux configs will eventually get Docker versions. 

I'm also hoping to start building versions of each distro as a generic OVA, so they can be downloaded standalone via the (Roboxes website)[https://roboxes.org/] ... but haven't found the time. 

As previously mentioned, building what I have setup already takes so long that it will be hard for me to add more variants until I get more/better hardware. Someone donated 4 blade servers, minus hard drives/memory earlier this year, and those husks are setup at my datacenter, but I didn't get a chance to install drives/memory/os'es before I left on my business trip to India...

As for the future, I've personally had my eye on porting some of the configs to the `vagrant-lxc` to provider, and eventually to the Amazon provider, but I don't personally know those ecosystems, so I haven't had the time. Same goes for Azure/Oracle and GCE.

Do you know how I could go about setting this up? Or better yet, do you have any interest in porting one of the `generic-*.json` files to one of these new platforms?

**Comment by MikePadge** [comment]
I'd be willing to try and invest some time into porting the generics to aws and azure. Do you have any notes, or workflow tips you could share or point me toward?

**Comment by mcandre** [comment]
Heh, I usually just search the github.org domain for packer template examples and trust the HashiCorp docs.
