### ISSUE TITLE
roboxes.org website broken link

### ISSUE THREAD

**Issue by LinuxNtwrkng** [lavabit/robox#57]
In the list of operating systems on https://roboxes.org, the link to RedHat has been incorrectly entered as https://https//www.redhat.com/en/technologies/linux-platforms/enterprise-linux  

Should be https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux

**Comment by LinuxNtwrkng** [comment]
I just noticed the same issue is present for the Microsoft link under Hypervisors as well.

https://https//www.microsoft.com/en-us/cloud-platform/server-virtualization should be https://www.microsoft.com/en-us/cloud-platform/server-virtualization
 (which is actually a redirect to https://azure.microsoft.com/en-us/services/virtual-machines/ so when this one gets fixed, may as well update it to the redirect, in my opinion)

**Comment by ladar** [comment]
Thank you for pointing out the broken links. They should be fixed now. 

I updated the Hyper-V link to point at https://docs.microsoft.com/en-us/virtualization/ since that site seemed more appropriate.
