### ISSUE TITLE
Debian 10 for Hyper-V: Why on the last build sometimes just 3 providers instead of the 5 ?

### ISSUE THREAD

**Issue by Yivan** [lavabit/robox#60]
Hello,

First thanks a lot for the work on building vagrant box and provide them to us !

I noticed that the last debian 10, don't provide Hyper-V sometimes. Is it a bug in the build system ?
Please see v1.9.19 and v1.9.14, no hyper-v, nor parralels:
https://app.vagrantup.com/generic/boxes/debian10
https://app.vagrantup.com/roboxes/boxes/debian10

The last Debian 10 (buster), v1.9.19, is the **stable** debian (all previous version are based on debian 10 testing). I would have very like to find Hyper-V as provider for this first one Debian 10 stable box.

Is it a bug or is a new build planned very soon for Hyper-V ?

Thanks !

**Comment by Yivan** [comment]
@ladar just noticed you answer partially to my questions here
https://github.com/lavabit/robox/issues/58#issuecomment-509141336

I hope you could access to hyperv soon !

**Comment by ladar** [comment]
@yivan it's not a mistake. I'm travelling in India, and even though I brought a Mac/Win machine, the inet connection is too slow (only 8 megabits max, usually less). That has made it really hard to rebuild the Parallels/HyperV images roughly every 2-3 weeks. To keep them showing up in the provider list though, I've been reusing existing images from previous releases. 

I did update the Debian 10 HyperV config, so in theory, if you have `packer` installed, and setup, you could try building an image locally with the following DOS commands:

```dos
git clone https://github.com/lavabit/robox/
cd robox
set VERSION=1.0.0
packer build -only=generic-debian10-hyperv generic-hyperv.json
```

**Comment by Yivan** [comment]
@ladar Thanks a lot to have making this update
Have a nice trip, wonderful human experience, India is a great country so contrasted.
