### ISSUE TITLE
Debian sid

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#62]
Please provide a base box for Debian sid, so that the very latest Debian packages can be directly used by VM's.

For example, sparc64-flavored g++ cross-compiler toolchains for amd64 guests, are available in sid but not buster.

https://packages.debian.org/search?suite=sid&arch=sparc64&searchon=names&keywords=g%2B%2B

https://packages.debian.org/search?suite=buster&arch=sparc64&searchon=names&keywords=g%2B%2B

**Comment by ladar** [comment]
@mcandre I looked into doing this at one point, but noticed the install process is a little more complicated. Making a "true" sid install from ISO difficult. But my biggest concern was that the unstable nature of sid would cause robox build process to break frequently, which means bots would have to wait ~1 hour for timeouts, and then it would require lots of dev hours I don't have debugging issues which might disappear when it's released. If this project ever gets dedicated build/dev resources, it would definitely be something I'm all for maintaining.

In theory, if you wanted this, just take the default buster image, and write a Vagrantfile which uses `sed` to point the  `/etc/apt/sources.list` file at "unstable". And then run `apt apt update` and `apt full-upgrade` and presto you have a have a sid environment.

You should add this to the robox wiki. And if you do write a Vagrantfile, add a page with instructions aka sample Vagrantfile which turns Debian 10 into sid. Most notably the sed command syntax that is required.

https://wiki.debian.org/DebianUnstable
