### ISSUE TITLE
update OpenBSD to 6.5

### ISSUE THREAD

**Issue by nusenu** [lavabit/robox#68]
OpeBSD 6.5 has been released on May 1, 2019.

https://www.openbsd.org/65.html

It would be great if you could update the OpenBSD box to 6.5

**Comment by ladar** [comment]
@nusenu thank you for letting me know. I missed that release announcement. It's too late for the 1.9.20 build, but the change should make it into the next build (at least for the VMWare, Virtualbox, libvirt images).
