### ISSUE TITLE
`emerge @world` broken for gentoo

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#71]
`emerge @world` no longer works for the latest Gentoo boxes. This is because Gentoo has begun requiring an explicit configuration for either `openssl` or `gnutls` dependency.

https://forums.gentoo.org/viewtopic-t-1088186.html?sid=cc6a015929bc644b1bf21e13a62cadb7

Can we go ahead and define one or the other in the base image, so that downstream boxes have a valid dependency tree?

**Comment by ladar** [comment]
Yes. How do I define OpenSSL by default?

**Comment by ladar** [comment]
@mcandre would the "best practice" be adding `openssl` to the `USE` setting in `/etc/portage/make.conf`?

**Comment by ladar** [comment]
Added `openssl` to the default USE params. Hopefully it fixes the issue. Building the 1.9.22 boxes now, but please reopen this issue if it isn't resolved.
