### ISSUE TITLE
Base box for OS/2 Warp

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#84]
Hi,

Could we get a base box published for OS/2 Warp? This would help to test legacy support for old C and Pascal applications.

Note that OS/2 Warp installation requires two virtual floppy disk insertions before loading the ISO.

This step does not appear to be automatable directly by Packer, requiring lower level `VBoxManage`, etc. commands to get to a state bootable by ISO virtual CD. Recommend exporting an OVF of the OS/2 Warp VM once it has gotten to the insert CD screen, then it is ready for Packer to complete the rest of the build.

https://winworldpc.com/product/os-2-warp-4/os-2-warp-40

**Comment by ladar** [comment]
In spirit, I support the idea, but in practice it doesn't make sense to create an OS/2 Robox, since the whole point is that I can automate the process, and thus rebuild the boxes periodically. Plus, the focus is on creating command line boxes, with SSH access.

**Comment by mcandre** [comment]
Good news! Floppy disk insertion and removal with Packer is reasonably easy to automate:

```json
      "vboxmanage": [
        ["modifyvm", "{{.Name}}", "--memory", "{{ user `ram_MiB` }}"],
        ["modifyvm", "{{.Name}}", "--vram", "{{ user `vram_MiB` }}"],
        ["modifyvm", "{{.Name}}", "--cpus", "{{ user `cpus` }}"],
        ["storagectl", "{{.Name}}", "--name", "Floppy Controller", "--add", "floppy"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Installation.img"],
        ["modifyvm", "{{.Name}}", "--boot1", "floppy"],
        ["modifyvm", "{{.Name}}", "--boot3", "disk"],
        ["startvm", "{{.Name}}"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Disk01.img"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "120000"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Disk02.img"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "30000"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Installation.img"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Disk01.img"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "120000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Disk02.img"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "300000"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "emptydrive"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "300000"],
        ["controlvm", "{{.Name}}", "poweroff"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "30000"]
      ],
```

Where the floppy IMG's and disc ISO's are downloaded from WinWorld archive and expanded to the host's temp directory.

https://cloudflare-ipfs.com/ipfs/QmeT1UrCw6eiNVV8ZeaeGhxwnUHV4hiH4quLUEMVT9rdYy/IBM%20OS2%20Warp%204.0%20(CD).7z

Even better news, OS/2 has an ssh server port:

http://www.altsan.org/os2/utils/

Those WPI's are installable by the WarpIN package manager.

http://warpin.netlabs.org/en/site/index.xml

Ordinarily, WarpIN uses a GUI to manage packages. But you can write an XCD file for the `wic [-i]` command line utility to process:

http://www.blondeguy.com/WarpINEssay.html

One last thing: RPM and Yum are highly recommended, as this secondary package manager provides a set of many important packages for any practical Vagrant box, such as wget and rsync. If you get this far, please also bundle a working yum setup into the OS/2 base box.

https://ecsoft2.org/rpmyum-os2

Finallly, VirtualBox has a critical bug with OS/2 guests: About 50% of boots silently fail. Retrying the Packer build is your friend, friend.

I'm still tinkering with my own OS/2 base box, but those are my notes so far.
