### ISSUE TITLE
generic/ubuntu1804 on vmware-provider missing hgfs shared folder not working

### ISSUE THREAD

**Issue by foxhunt72** [lavabit/robox#87]
the vmware generic/ubuntu1804 box is missing the vmware clients install and shared folder hgfs is not working

**Comment by foxhunt72** [comment]
It seems to work, if i use

config.vm.synced_folder ".", "/vagrant", disabled: false

**Comment by ladar** [comment]
@foxhunt72 the bundled `Vagrantfile` contains `config.vm.synced_folder ".", "/vagrant", disabled: true` because to avoid problems, as not all of the distros support sync'ed folders on all of the supported hosts. Obviously it can be easily overridden with an explicit directive, like you noted above.
