### ISSUE TITLE
generic/debian10 shared folders not working

### ISSUE THREAD

**Issue by ltoenning** [lavabit/robox#88]
With the lastet generic/debian10 box the shared folders cannot be mounted.

The mount command fails with: "No such device".

**Comment by ladar** [comment]
I don't know. I would need more advice, like a `Vagrantfile` capable of duplicating the problem, and to know what platform your host is running. You might also want to look at #87.

**Comment by ltoenning** [comment]
Didn't saw #87. Now it works. Thanks!
