### ISSUE TITLE
generic/fedora30 - image won't start due "Timed out waiting for device"

### ISSUE THREAD

**Issue by djhworld** [lavabit/robox#96]
Using vagrant, vagrant-libvirt

When trying to run this image it just hangs

<img width="719" alt="screenshot 2019-10-27 at 22 15 16" src="https://user-images.githubusercontent.com/529730/67642796-68367f00-f907-11e9-9198-4d744f067a54.png">

It looks like it's expecting some disk to be a attached but it isn't there.

This causes Vagrant to get stuck in the state

```
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
```

Note this was also noticed in https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1032#issuecomment-540009214

**Comment by defanator** [comment]
Seeing the same with `generic/fedora29` (1.9.38), `generic/fedora30` (1.9.38) on vagrant 2.2.6 with libvirt 0.0.45.

**Comment by defanator** [comment]
Also, the same thing with `generic/opensuse42` image.

**Comment by tomaskrizek** [comment]
I reproduced the issue when using `libvirt` with the `generic/fedora30` and `generic/opensuse15` boxes. I was able to get the boxes to boot by using:

```
  config.vm.provider :libvirt do |v, override|
    v.disk_bus = "sata"
  end
```

Related issue: https://github.com/lavabit/robox/issues/94

**Comment by pavlix** [comment]
I confirm the workaround by @tomaskrizek with `generic/opensuse15`. Does that mean `generic/opensuse*` images need to be rebuild with the `virtio` configuration?

**Comment by ladar** [comment]
See #125.
