### ISSUE TITLE
generic/ubuntu1910?

### ISSUE THREAD

**Issue by yombo** [lavabit/robox#97]
Hey ya. Thanks for doing this! Any chance to get Ubuntu 19.10 added? Thanks.

**Comment by ladar** [comment]
@yombo I'm working on Fedora 31 and Ubuntu 19.10. Hopefully soon.

**Comment by yombo** [comment]
Thanks!  It looks like you completed this in: 3ca131de3eee9cf9c2a7cd1734d659553b77cbc1

This is very much appreciated.
